### ISSUE TITLE
Missing License File

### ISSUE THREAD

**Issue by nmbgeek** [PulseMeshLabs/fpp-pulsemesh#7]
Both the existing PulseMesh plugin repos and pulsemesh.io site seem to be missing any licensing information.  Edited to remove incorrect information.

**Comment by rdkbob** [comment]
Appreciate your question.  I agree, in alignment with your edit, that PulseMesh is not a derivative work under GPL.  FPPMon (https://github.com/KulpLights/fpp-FPPMon) built by Danial Kulp is a similar example of a non-OS FPP plugin.  There are no current plans to release the PulseMesh code base under an OS license, hence one is not applied to this repository.
